version: "3.8"

services:

  redis:
    container_name: redis-service
    image: redis:7
    restart: always

  db:
    container_name: database-service
    image: mysql:8.3.0
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -pP@55w0rd!" ]
      timeout: 20s
      retries: 10

  app:
    container_name: django-web
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app/
      - static-data:/vol/web/static
      - media-data:/vol/web/media
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db

  celery:
    restart: always
    container_name: celery-worker
    build:
      context: .
    entrypoint: /scripts/worker-entrypoint.sh
#    command: celery --app=hydrocarbures worker -l INFO -c 4
    volumes:
      - .:/usr/src/app/
      - static-data:/vol/web/static
      - media-data:/vol/web/media
    env_file:
      - .env
    depends_on:
      - app
      - redis

  flower:
    container_name: flower-service
    image: mher/flower
    command: celery --broker=redis://redis:6379 flower
    ports:
      - 5555:5555
    depends_on:
      - redis

#  proxy:
#    container_name: proxy-service
#    build:
#      context: ./proxy
#    volumes:
#      - .:/usr/src/app/
#      - static-data:/vol/web/static
#      - media-data:/vol/web/media
#    ports:
#      - "80:80"
#    depends_on:
#      - app

volumes:
  static-data:
  media-data:
