apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlOREF6TWpVdwpPVFE0TkRkYUZ3MDBOREF6TWpVd09UUTRORGRhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFERXJKY1VZRWFVMC83djJJVHV5ZmRWZE82QzNvNFp0RUxyRVNuN2ZmMHNwSXFGbkNjcAorYzMvUFBXN0hnZll5eXJYZGRsQytJajNUVzJ1UVIwc09HaElCM1ZNMUdVMU04cDY0WkJXMHMrVjFWS0JSME5nCktJTTFkY0NMVFdiSSs4Q2IyTlV5VkFxYUYxTWQ2TDBZWm5ndDZ5VHBRY2Y5cDFHSE9id0tkQmxJWFo4WGFiOU8KcW1aL2E1UjJSTGt2Z0RobDduQVlYVmU2cEFveXkweVNhbFV1dUMxVU1FSVRoMUxMa1BWdmFZTHJhOU00NkRxVgpmZFlYWXhkT2xUWE9CL1BOSFJzTkRJWk5IUmFjYlpySzcrQ3MyU3R1L28vZFdTTXZ3WWZHc1k3SHE4a25WSGJnClBSZVpQN1FXM1E4dkpUWHNoZUc5NDZOUVZaRHJmaktRUldLSkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlQ0NFIrMHBMM2RnZXJWWVJTMAorMXFUNFY5dVNUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFKdy94TllIa0JhdEdZT2FReFgvMEFkeURhNDNMClFYQXBaT2xCVkNOVENlMlJDWjVkeUJrcmFVNWg0bytTMHFRVEF6V1hzMm1JZkc2WHNFUXdqNjdkY1FUTVJsY3cKUEp5eEpmazArRmY5ejBlTTB2TStJRG1IdkV2WS9WNFdRb29yTmtpZ24vc01KMkl5VTVzVmEvNnZBVHdsMzJ4QgpCMHV5L0FYdFRlTWNhUzZGaGY4TDJBUmdNS1pzci9SZ2J4SE5uSHR2T3BMaExUUGtZbWZUTG14UkJIVGF1ay9ICllxOC8rdnFLQmZNNmF2TmsyMlM0K1ZMaTZaVWRSaWJqZFZVM1M1UDA2Qm9DQjN1dVVPM0EzdTloTjIzY25oWEgKNWtVNjBlTWhDV1BnUlFGQkkwUHZSM29qSTgzVXJ6NUVRTkZFemc5NE16TzhsU2RZVHNVM1FZQWFoZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://33a78c0d-3e18-4318-a303-0187ea909d12.k8s.ondigitalocean.com
  name: do-sfo3-k8s-gestionhydro
contexts:
- context:
    cluster: do-sfo3-k8s-gestionhydro
    user: do-sfo3-k8s-gestionhydro-admin
  name: do-sfo3-k8s-gestionhydro
current-context: do-sfo3-k8s-gestionhydro
kind: Config
preferences: {}
users:
- name: do-sfo3-k8s-gestionhydro-admin
  user:
    token: dop_v1_982b90b5e4c3abb06b8562600c66472a1021dcbe3af3c201b879d21c3719f90c
