# Generated by Django 3.1.1 on 2020-09-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enreg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargaison',
            name='l_control',
            field=models.IntegerField(null=True),
        ),
    ]
