# Generated by Django 4.2.10 on 2024-05-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enreg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargaison',
            name='files_path',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='cargaison',
            name='numCertInspection',
            field=models.IntegerField(null=True),
        ),
    ]
