# Generated by Django 4.2.10 on 2024-05-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enreg', '0002_cargaison_files_path_cargaison_numcertinspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargaison',
            name='controlLiquidation',
            field=models.BooleanField(default=False),
        ),
    ]
