# Generated by Django 4.2.10 on 2024-05-15 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enreg', '0003_cargaison_controlliquidation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidationModel',
            fields=[
                ('idLiquidationMod', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('liquidationModel', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='liquidation',
            name='bankName',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='liquidation',
            name='datepay',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liquidation',
            name='datebl',
            field=models.DateField(blank=True, null=True, verbose_name='Date de BL'),
        ),
        migrations.AddField(
            model_name='liquidation',
            name='modele',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='enreg.liquidationmodel'),
        ),
    ]
