# Generated by Django 4.2.10 on 2024-05-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enreg', '0004_liquidationmodel_liquidation_bankname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidation',
            name='type_appurement',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
