# Generated by Django 4.2.10 on 2024-05-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enreg', '0005_alter_liquidation_type_appurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidation',
            name='user',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
