# Generated by Django 4.2.10 on 2024-05-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enreg', '0006_liquidation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargaison',
            name='partialLiquidattion',
            field=models.BooleanField(default=False),
        ),
    ]
