# Generated by Django 4.2.23 on 2025-09-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enreg', '0007_cargaison_partialliquidattion'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepot_echantillon',
            name='notes',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
