# Generated by Django 4.1 on 2023-11-03 06:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enreg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code="Nom d'utilisateur invalid", message="Le nom d'utilisateur doit etre alphanumerique", regex='^[a-zA-Z0-9.+-]*$')])),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('fonction', models.CharField(blank=True, max_length=256, null=True)),
                ('poste', models.CharField(blank=True, max_length=100, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListeLaboratoire',
            fields=[
                ('idLaboratoire', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('denominationLaboratoire', models.CharField(blank=True, max_length=64, null=True)),
                ('adresseLaboratoire', models.CharField(blank=True, max_length=64, null=True)),
                ('typeLaboratoire', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('idrole', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=32, verbose_name='Role')),
            ],
        ),
        migrations.CreateModel(
            name='AffectationVille',
            fields=[
                ('idaffectation_ville', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enreg.ville')),
            ],
        ),
        migrations.CreateModel(
            name='AffectationLaboratoire',
            fields=[
                ('idAffectation', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('signGauche', models.BooleanField(blank=True, null=True)),
                ('idLaboratoire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.listelaboratoire')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enreg.ville')),
            ],
        ),
        migrations.CreateModel(
            name='AffectationEntrepot',
            fields=[
                ('idaffectation_entrepot', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enreg.entrepot')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.roles'),
        ),
    ]
