apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestionhydro-deployment
  labels:
    app: gestionhydro-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gestionhydro-deployment
  template:
    metadata:
      labels:
        app: gestionhydro-deployment
    spec:
      imagePullSecrets:
        - name: otace
      containers:
        - name: django-server
          image: registry.digitalocean.com/otace/gestionhydro-amd64:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: django-deploy-env
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "2Gi"   # Request 2GB of RAM
              cpu: "0.5"      # Request 0.5 vCPU
            limits:
              memory: "2.5Gi" # Limit to 2.5GB of RAM
              cpu: "1"        # Limit to 1 vCPU
          command: [ "/bin/sh", "-c", "gunicorn hydrocarbures.wsgi --bind 0.0.0.0:8000 --worker-tmp-dir /dev/shm" ]
        - name: celery-worker
          image: registry.digitalocean.com/otace/gestionhydro-amd64:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: django-deploy-env
          resources:
            requests:
              memory: "1Gi"   # Request 1GB of RAM
              cpu: "0.5"      # Request 0.5 vCPU
            limits:
              memory: "1.5Gi" # Limit to 1.5GB of RAM
              cpu: "1"        # Limit to 1 vCPU
          command: [ "/bin/sh", "-c", "celery -A hydrocarbures worker --loglevel=info" ]
        - name: redis-server
          image: redis
          ports:
            - protocol: TCP
              containerPort: 6379
          resources:
            requests:
              memory: "500Mi" # Request 500MB of RAM
              cpu: "0.2"      # Request 0.2 vCPU
            limits:
              memory: "1Gi"   # Limit to 1GB of RAM
              cpu: "0.5"      # Limit to 0.5 vCPU
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-configmap
