name: Django Tests

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: ["Dockerized"]
  pull_request:
    branches: ["Dockerized"]

concurrency:
  group: django-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install security tools
        run: pip install bandit

      - name: Bandit Scan
        # -r: recursive, -ll: medium/high severity, -x: exclude directories
        run: bandit -r . -ll -x ./tests,./venv,./migrations,./staticfiles,./staticfiles-cdn,./static,./assets
